development: 
  access_key_id: <%=ENV["AWS_ACCESS_KEY_ID"]%>
  bucket: <%=ENV["AWS_BUCKET"]%>
  secret_access_key: <%=ENV["AWS_SECRET_ACCESS_KEY"]%>
  region: <%=ENV["AWS_REGION"]%>
production: 
  access_key_id: <%=ENV["AWS_ACCESS_KEY_ID"]%>
  bucket: <%=ENV["AWS_BUCKET"]%>
  secret_access_key: <%=ENV["AWS_SECRET_ACCESS_KEY"]%>
  region: <%=ENV["AWS_REGION"]%>
test: 
  access_key_id: <%=ENV["AWS_ACCESS_KEY_ID"]%>
  bucket: <%=ENV["AWS_BUCKET"]%>
  secret_access_key: <%=ENV["AWS_SECRET_ACCESS_KEY"]%>
  region: <%=ENV["AWS_REGION"]%>